//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aprobacion
    {
        public int IdAprobacion { get; set; }
        public Nullable<int> IdUsuarioAprobador { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string Estado { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
