//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoWebRendicion
    {
        public int IdDocumentoWebRendicion { get; set; }
        public int IdDocumentoWeb { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public int NumeroRendicion { get; set; }
        public string SAPCodigoPartidaPresupuestal { get; set; }
        public string SAPCodigoConcepto { get; set; }
        public string SAPCodigoCentroCostos1 { get; set; }
        public string SAPCodigoCentroCostos2 { get; set; }
        public string SAPCodigoCentroCostos3 { get; set; }
        public string SAPCodigoCentroCostos4 { get; set; }
        public string SAPCodigoCentroCostos5 { get; set; }
        public string SAPCodigoCuentaContableRendicion { get; set; }
        public int IdTipoDocSunat { get; set; }
        public string SerieDoc { get; set; }
        public int CorrelativoDoc { get; set; }
        public System.DateTime FechaDoc { get; set; }
        public int IdMonedaDoc { get; set; }
        public decimal MontoDoc { get; set; }
        public decimal MontoTasaCambio { get; set; }
        public decimal MontoNoAfecto { get; set; }
        public decimal MontoAfecto { get; set; }
        public decimal MontoIGV { get; set; }
        public decimal MontoTotal { get; set; }
        public int EstadoRendicion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UserUpdate { get; set; }
        public int IdUsuarioModificacion { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Documento Documento1 { get; set; }
        public virtual Documento Documento2 { get; set; }
        public virtual DocumentoWeb DocumentoWeb { get; set; }
        public virtual DocumentoWeb DocumentoWeb1 { get; set; }
        public virtual DocumentoWeb DocumentoWeb2 { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Moneda Moneda1 { get; set; }
        public virtual Moneda Moneda2 { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Proveedor Proveedor1 { get; set; }
        public virtual Proveedor Proveedor2 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Usuario Usuario3 { get; set; }
        public virtual Usuario Usuario4 { get; set; }
        public virtual Usuario Usuario5 { get; set; }
    }
}
