//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoWebAuditoria
    {
        public int IdDocumentoWebAuditoria { get; set; }
        public int IdDocumentoWeb { get; set; }
        public int EstadoDocumento { get; set; }
        public string Comentario { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual DocumentoWeb DocumentoWeb { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
