//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoWeb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentoWeb()
        {
            this.DocumentoWebAuditoria = new HashSet<DocumentoWebAuditoria>();
            this.DocumentoWebRendicion = new HashSet<DocumentoWebRendicion>();
            this.DocumentoWebRendicion1 = new HashSet<DocumentoWebRendicion>();
            this.DocumentoWebRendicion2 = new HashSet<DocumentoWebRendicion>();
        }
    
        public int IdDocumentoWeb { get; set; }
        public string Codigo { get; set; }
        public int TipoDocumentoWeb { get; set; }
        public int IdUsuarioSolicitante { get; set; }
        public int NumeroRendicion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string SAPCodigoCentroCostos1 { get; set; }
        public string SAPCodigoCentroCostos2 { get; set; }
        public string SAPCodigoCentroCostos3 { get; set; }
        public string SAPCodigoCentroCostos4 { get; set; }
        public string SAPCodigoCentroCostos5 { get; set; }
        public Nullable<int> IdMetodoPago { get; set; }
        public decimal MontoInicial { get; set; }
        public int IdMoneda { get; set; }
        public string Asunto { get; set; }
        public string Comentario { get; set; }
        public string MotivoDetalle { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaContabilizacion { get; set; }
        public int EstadoDocumento { get; set; }
        public Nullable<int> IdDocumentoWebRendicionReferencia { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebAuditoria> DocumentoWebAuditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion2 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
