//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.DocumentoWebRendicion = new HashSet<DocumentoWebRendicion>();
            this.DocumentoWebRendicion1 = new HashSet<DocumentoWebRendicion>();
            this.DocumentoWebRendicion2 = new HashSet<DocumentoWebRendicion>();
        }
    
        public int IdDocumento { get; set; }
        public string Descripcion { get; set; }
        public string CodigoSunat { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion2 { get; set; }
    }
}
