//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresasSICER
    {
        public int IdEmpresaSICER { get; set; }
        public int IdInterno { get; set; }
        public string Codigo { get; set; }
        public string RazonSocial { get; set; }
    }
}
