//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public int EstadoCode { get; set; }
        public string EstadoNombre { get; set; }
        public string EstadoDescripcion { get; set; }
    }
}
