//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelAprobacion
    {
        public int IdNivel { get; set; }
        public string Descripcion { get; set; }
        public string Nivel { get; set; }
        public string Documento { get; set; }
        public string EsDeMonto { get; set; }
        public string Monto { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
