//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SICER_INT_SBOEntities : DbContext
    {
        public SICER_INT_SBOEntities()
            : base("name=SICER_INT_SBOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FacturasWebMigracion> FacturasWebMigracion { get; set; }
        public virtual DbSet<MaestroTrabajadores> MaestroTrabajadores { get; set; }
        public virtual DbSet<DetalleAsientos> DetalleAsientos { get; set; }
        public virtual DbSet<TD_DOCU_RETE> TD_DOCU_RETE { get; set; }
    
        public virtual ObjectResult<MSS_SP_SICER_ACCOUNTINFO_Result> MSS_SP_SICER_ACCOUNTINFO(string curr, Nullable<System.DateTime> date, string cC5)
        {
            var currParameter = curr != null ?
                new ObjectParameter("Curr", curr) :
                new ObjectParameter("Curr", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var cC5Parameter = cC5 != null ?
                new ObjectParameter("CC5", cC5) :
                new ObjectParameter("CC5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_ACCOUNTINFO_Result>("MSS_SP_SICER_ACCOUNTINFO", currParameter, dateParameter, cC5Parameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_ACCOUNTPAYMENTS_Result> MSS_SP_SICER_ACCOUNTPAYMENTS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_ACCOUNTPAYMENTS_Result>("MSS_SP_SICER_ACCOUNTPAYMENTS");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_BUSINESSPARTNERS_Result> MSS_SP_SICER_BUSINESSPARTNERS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_BUSINESSPARTNERS_Result>("MSS_SP_SICER_BUSINESSPARTNERS");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_CUENTASPAGO_Result> MSS_SP_SICER_CUENTASPAGO(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_CUENTASPAGO_Result>("MSS_SP_SICER_CUENTASPAGO", codeParameter);
        }
    
        public virtual int MSS_SP_SICER_CUENTASVALIDAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_SP_SICER_CUENTASVALIDAS");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_DATOSERETAPA1_Result> MSS_SP_SICER_DATOSERETAPA1(Nullable<int> exCode)
        {
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_DATOSERETAPA1_Result>("MSS_SP_SICER_DATOSERETAPA1", exCodeParameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_FACTURACIONWEB_Result> MSS_SP_SICER_FACTURACIONWEB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_FACTURACIONWEB_Result>("MSS_SP_SICER_FACTURACIONWEB");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_FACTURACIONWEBDETALLE_Result> MSS_SP_SICER_FACTURACIONWEBDETALLE(Nullable<int> exCode, Nullable<int> docType, Nullable<int> etapa, Nullable<int> idFactura)
        {
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            var docTypeParameter = docType.HasValue ?
                new ObjectParameter("DocType", docType) :
                new ObjectParameter("DocType", typeof(int));
    
            var etapaParameter = etapa.HasValue ?
                new ObjectParameter("Etapa", etapa) :
                new ObjectParameter("Etapa", typeof(int));
    
            var idFacturaParameter = idFactura.HasValue ?
                new ObjectParameter("IdFactura", idFactura) :
                new ObjectParameter("IdFactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_FACTURACIONWEBDETALLE_Result>("MSS_SP_SICER_FACTURACIONWEBDETALLE", exCodeParameter, docTypeParameter, etapaParameter, idFacturaParameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_FACTURASRENDIDASER_Result> MSS_SP_SICER_FACTURASRENDIDASER(Nullable<int> exCode, string curr)
        {
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            var currParameter = curr != null ?
                new ObjectParameter("Curr", curr) :
                new ObjectParameter("Curr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_FACTURASRENDIDASER_Result>("MSS_SP_SICER_FACTURASRENDIDASER", exCodeParameter, currParameter);
        }
    
        public virtual ObjectResult<string> MSS_SP_SICER_GETACCOUNTFROMCONFIG(string u_Documento, string u_codigo)
        {
            var u_DocumentoParameter = u_Documento != null ?
                new ObjectParameter("U_Documento", u_Documento) :
                new ObjectParameter("U_Documento", typeof(string));
    
            var u_codigoParameter = u_codigo != null ?
                new ObjectParameter("U_codigo", u_codigo) :
                new ObjectParameter("U_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MSS_SP_SICER_GETACCOUNTFROMCONFIG", u_DocumentoParameter, u_codigoParameter);
        }
    
        public virtual int MSS_SP_SICER_GRUPOSFACTURACION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_SP_SICER_GRUPOSFACTURACION");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_JOURNALENTRIESHEADER_Result> MSS_SP_SICER_JOURNALENTRIESHEADER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_JOURNALENTRIESHEADER_Result>("MSS_SP_SICER_JOURNALENTRIESHEADER");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_JOURNALENTRIESLINES_Result> MSS_SP_SICER_JOURNALENTRIESLINES(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_JOURNALENTRIESLINES_Result>("MSS_SP_SICER_JOURNALENTRIESLINES", idParameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_PAYROLLINVOICES_Result> MSS_SP_SICER_PAYROLLINVOICES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_PAYROLLINVOICES_Result>("MSS_SP_SICER_PAYROLLINVOICES");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_PENDINGINVOICES_Result> MSS_SP_SICER_PENDINGINVOICES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_PENDINGINVOICES_Result>("MSS_SP_SICER_PENDINGINVOICES");
        }
    
        public virtual ObjectResult<Nullable<int>> MSS_SP_SICER_PRIMERAETAPA(Nullable<int> exCode)
        {
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MSS_SP_SICER_PRIMERAETAPA", exCodeParameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_PURCHASEINVOICES_Result> MSS_SP_SICER_PURCHASEINVOICES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_PURCHASEINVOICES_Result>("MSS_SP_SICER_PURCHASEINVOICES");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_PURCHASEINVOICESLINES_Result> MSS_SP_SICER_PURCHASEINVOICESLINES(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_PURCHASEINVOICESLINES_Result>("MSS_SP_SICER_PURCHASEINVOICESLINES", idParameter);
        }
    
        public virtual ObjectResult<MSS_SP_SICER_REFACTURABLES_Result> MSS_SP_SICER_REFACTURABLES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_REFACTURABLES_Result>("MSS_SP_SICER_REFACTURABLES");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_RENDICIONESSEGUNDAETAPA_Result> MSS_SP_SICER_RENDICIONESSEGUNDAETAPA(Nullable<int> exCode, string curr)
        {
            var exCodeParameter = exCode.HasValue ?
                new ObjectParameter("ExCode", exCode) :
                new ObjectParameter("ExCode", typeof(int));
    
            var currParameter = curr != null ?
                new ObjectParameter("Curr", curr) :
                new ObjectParameter("Curr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_RENDICIONESSEGUNDAETAPA_Result>("MSS_SP_SICER_RENDICIONESSEGUNDAETAPA", exCodeParameter, currParameter);
        }
    
        public virtual int MSS_SP_SICER_TRASLADOFACTURAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_SP_SICER_TRASLADOFACTURAS");
        }
    
        public virtual ObjectResult<MSS_SP_SICER_WEBUDOINVOICES_Result> MSS_SP_SICER_WEBUDOINVOICES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_SP_SICER_WEBUDOINVOICES_Result>("MSS_SP_SICER_WEBUDOINVOICES");
        }
    
        [DbFunction("SICER_INT_SBOEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[SICER_INT_SBOEntities].[Split](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        [DbFunction("SICER_INT_SBOEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string str, string separator)
        {
            var strParameter = str != null ?
                new ObjectParameter("str", str) :
                new ObjectParameter("str", typeof(string));
    
            var separatorParameter = separator != null ?
                new ObjectParameter("separator", separator) :
                new ObjectParameter("separator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[SICER_INT_SBOEntities].[SplitString](@str, @separator)", strParameter, separatorParameter);
        }
    
        public virtual int UpdateCostingCodes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCostingCodes");
        }
    
        public virtual int UpdateCurrency()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCurrency");
        }
    
        public virtual int UpdateGroups()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateGroups");
        }
    
        public virtual int UpdatePaymentGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePaymentGroup");
        }
    
        public virtual int UpdatePayMethods()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePayMethods");
        }
    
        public virtual int UpdateRefIndex()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateRefIndex");
        }
    
        public virtual int USP_INS_COMP_RETE_005(string cO_IDEN, string nU_RUCS, string dE_EMPR, string dE_DIRE, string dE_DPTO, string dE_PROV, string dE_DIST, Nullable<System.DateTime> fE_EMIS, string dE_MOTI, string cO_TIPO_DOCU, string cO_SERI, string nU_CORR, string cO_ESTA, string cO_VERS_UBL, string cO_VERS_ESTR, Nullable<int> nU_ORDE, string cO_SERI_DREL, string nU_CORR_DREL, string cO_TIPO_DREL, Nullable<System.DateTime> fE_EMIS_DREL)
        {
            var cO_IDENParameter = cO_IDEN != null ?
                new ObjectParameter("CO_IDEN", cO_IDEN) :
                new ObjectParameter("CO_IDEN", typeof(string));
    
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var dE_EMPRParameter = dE_EMPR != null ?
                new ObjectParameter("DE_EMPR", dE_EMPR) :
                new ObjectParameter("DE_EMPR", typeof(string));
    
            var dE_DIREParameter = dE_DIRE != null ?
                new ObjectParameter("DE_DIRE", dE_DIRE) :
                new ObjectParameter("DE_DIRE", typeof(string));
    
            var dE_DPTOParameter = dE_DPTO != null ?
                new ObjectParameter("DE_DPTO", dE_DPTO) :
                new ObjectParameter("DE_DPTO", typeof(string));
    
            var dE_PROVParameter = dE_PROV != null ?
                new ObjectParameter("DE_PROV", dE_PROV) :
                new ObjectParameter("DE_PROV", typeof(string));
    
            var dE_DISTParameter = dE_DIST != null ?
                new ObjectParameter("DE_DIST", dE_DIST) :
                new ObjectParameter("DE_DIST", typeof(string));
    
            var fE_EMISParameter = fE_EMIS.HasValue ?
                new ObjectParameter("FE_EMIS", fE_EMIS) :
                new ObjectParameter("FE_EMIS", typeof(System.DateTime));
    
            var dE_MOTIParameter = dE_MOTI != null ?
                new ObjectParameter("DE_MOTI", dE_MOTI) :
                new ObjectParameter("DE_MOTI", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_ESTAParameter = cO_ESTA != null ?
                new ObjectParameter("CO_ESTA", cO_ESTA) :
                new ObjectParameter("CO_ESTA", typeof(string));
    
            var cO_VERS_UBLParameter = cO_VERS_UBL != null ?
                new ObjectParameter("CO_VERS_UBL", cO_VERS_UBL) :
                new ObjectParameter("CO_VERS_UBL", typeof(string));
    
            var cO_VERS_ESTRParameter = cO_VERS_ESTR != null ?
                new ObjectParameter("CO_VERS_ESTR", cO_VERS_ESTR) :
                new ObjectParameter("CO_VERS_ESTR", typeof(string));
    
            var nU_ORDEParameter = nU_ORDE.HasValue ?
                new ObjectParameter("NU_ORDE", nU_ORDE) :
                new ObjectParameter("NU_ORDE", typeof(int));
    
            var cO_SERI_DRELParameter = cO_SERI_DREL != null ?
                new ObjectParameter("CO_SERI_DREL", cO_SERI_DREL) :
                new ObjectParameter("CO_SERI_DREL", typeof(string));
    
            var nU_CORR_DRELParameter = nU_CORR_DREL != null ?
                new ObjectParameter("NU_CORR_DREL", nU_CORR_DREL) :
                new ObjectParameter("NU_CORR_DREL", typeof(string));
    
            var cO_TIPO_DRELParameter = cO_TIPO_DREL != null ?
                new ObjectParameter("CO_TIPO_DREL", cO_TIPO_DREL) :
                new ObjectParameter("CO_TIPO_DREL", typeof(string));
    
            var fE_EMIS_DRELParameter = fE_EMIS_DREL.HasValue ?
                new ObjectParameter("FE_EMIS_DREL", fE_EMIS_DREL) :
                new ObjectParameter("FE_EMIS_DREL", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_COMP_RETE_005", cO_IDENParameter, nU_RUCSParameter, dE_EMPRParameter, dE_DIREParameter, dE_DPTOParameter, dE_PROVParameter, dE_DISTParameter, fE_EMISParameter, dE_MOTIParameter, cO_TIPO_DOCUParameter, cO_SERIParameter, nU_CORRParameter, cO_ESTAParameter, cO_VERS_UBLParameter, cO_VERS_ESTRParameter, nU_ORDEParameter, cO_SERI_DRELParameter, nU_CORR_DRELParameter, cO_TIPO_DRELParameter, fE_EMIS_DRELParameter);
        }
    
        public virtual int USP_INS_TD_DOCU_SUNA_001(string cO_IDEN, string nU_RUCS, string dE_EMPR, string dE_DIRE, string dE_DPTO, string dE_PROV, string dE_DIST, string cO_IDEN_DEST, string nU_RUCS_DEST, Nullable<System.DateTime> fE_EMIS, string dE_MOTI_BAJA, string cO_TIPO_DOCU, string cO_SERI, string nU_CORR, string cO_MONE, string cO_ESTA, string cO_VERS_UBL, string cO_VERS_ESTR, string nU_ORDE, string nU_SERI_DMOD, string nU_CORR_DMOD, string cO_TIPO_DMOD, string cO_SERI_DREL, string nU_CORR_DREL, string nU_CORR_FINA, string cO_TIPO_DREL, Nullable<System.DateTime> fE_EMIS_DREL, Nullable<decimal> nU_DIGV, string cO_IDEN_DIGV, string dE_DIGV, string cO_TIPO_DIGV, Nullable<decimal> nU_DISC, string cO_IDEN_DISC, string dE_IDEN_DISC, string cO_TIPO_DISC, Nullable<decimal> nU_TOTA_TRIB, string cO_TRIB, string dE_TRIB, string cO_TIPO_TRIB, Nullable<decimal> nU_TOTA_CARG, string tI_SOTR_CARG, string cO_OPER_GRAB, Nullable<decimal> nU_OPER_GRAB, string cO_OPER_INAF, Nullable<decimal> nU_OPER_INAF, string cO_OPER_EXON, Nullable<decimal> nU_OPER_EXON, Nullable<decimal> nU_TOTA, string cO_ESTA_ITEM, string cO_OPER_GRAT, Nullable<decimal> nU_OPER_GRAT)
        {
            var cO_IDENParameter = cO_IDEN != null ?
                new ObjectParameter("CO_IDEN", cO_IDEN) :
                new ObjectParameter("CO_IDEN", typeof(string));
    
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var dE_EMPRParameter = dE_EMPR != null ?
                new ObjectParameter("DE_EMPR", dE_EMPR) :
                new ObjectParameter("DE_EMPR", typeof(string));
    
            var dE_DIREParameter = dE_DIRE != null ?
                new ObjectParameter("DE_DIRE", dE_DIRE) :
                new ObjectParameter("DE_DIRE", typeof(string));
    
            var dE_DPTOParameter = dE_DPTO != null ?
                new ObjectParameter("DE_DPTO", dE_DPTO) :
                new ObjectParameter("DE_DPTO", typeof(string));
    
            var dE_PROVParameter = dE_PROV != null ?
                new ObjectParameter("DE_PROV", dE_PROV) :
                new ObjectParameter("DE_PROV", typeof(string));
    
            var dE_DISTParameter = dE_DIST != null ?
                new ObjectParameter("DE_DIST", dE_DIST) :
                new ObjectParameter("DE_DIST", typeof(string));
    
            var cO_IDEN_DESTParameter = cO_IDEN_DEST != null ?
                new ObjectParameter("CO_IDEN_DEST", cO_IDEN_DEST) :
                new ObjectParameter("CO_IDEN_DEST", typeof(string));
    
            var nU_RUCS_DESTParameter = nU_RUCS_DEST != null ?
                new ObjectParameter("NU_RUCS_DEST", nU_RUCS_DEST) :
                new ObjectParameter("NU_RUCS_DEST", typeof(string));
    
            var fE_EMISParameter = fE_EMIS.HasValue ?
                new ObjectParameter("FE_EMIS", fE_EMIS) :
                new ObjectParameter("FE_EMIS", typeof(System.DateTime));
    
            var dE_MOTI_BAJAParameter = dE_MOTI_BAJA != null ?
                new ObjectParameter("DE_MOTI_BAJA", dE_MOTI_BAJA) :
                new ObjectParameter("DE_MOTI_BAJA", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_MONEParameter = cO_MONE != null ?
                new ObjectParameter("CO_MONE", cO_MONE) :
                new ObjectParameter("CO_MONE", typeof(string));
    
            var cO_ESTAParameter = cO_ESTA != null ?
                new ObjectParameter("CO_ESTA", cO_ESTA) :
                new ObjectParameter("CO_ESTA", typeof(string));
    
            var cO_VERS_UBLParameter = cO_VERS_UBL != null ?
                new ObjectParameter("CO_VERS_UBL", cO_VERS_UBL) :
                new ObjectParameter("CO_VERS_UBL", typeof(string));
    
            var cO_VERS_ESTRParameter = cO_VERS_ESTR != null ?
                new ObjectParameter("CO_VERS_ESTR", cO_VERS_ESTR) :
                new ObjectParameter("CO_VERS_ESTR", typeof(string));
    
            var nU_ORDEParameter = nU_ORDE != null ?
                new ObjectParameter("NU_ORDE", nU_ORDE) :
                new ObjectParameter("NU_ORDE", typeof(string));
    
            var nU_SERI_DMODParameter = nU_SERI_DMOD != null ?
                new ObjectParameter("NU_SERI_DMOD", nU_SERI_DMOD) :
                new ObjectParameter("NU_SERI_DMOD", typeof(string));
    
            var nU_CORR_DMODParameter = nU_CORR_DMOD != null ?
                new ObjectParameter("NU_CORR_DMOD", nU_CORR_DMOD) :
                new ObjectParameter("NU_CORR_DMOD", typeof(string));
    
            var cO_TIPO_DMODParameter = cO_TIPO_DMOD != null ?
                new ObjectParameter("CO_TIPO_DMOD", cO_TIPO_DMOD) :
                new ObjectParameter("CO_TIPO_DMOD", typeof(string));
    
            var cO_SERI_DRELParameter = cO_SERI_DREL != null ?
                new ObjectParameter("CO_SERI_DREL", cO_SERI_DREL) :
                new ObjectParameter("CO_SERI_DREL", typeof(string));
    
            var nU_CORR_DRELParameter = nU_CORR_DREL != null ?
                new ObjectParameter("NU_CORR_DREL", nU_CORR_DREL) :
                new ObjectParameter("NU_CORR_DREL", typeof(string));
    
            var nU_CORR_FINAParameter = nU_CORR_FINA != null ?
                new ObjectParameter("NU_CORR_FINA", nU_CORR_FINA) :
                new ObjectParameter("NU_CORR_FINA", typeof(string));
    
            var cO_TIPO_DRELParameter = cO_TIPO_DREL != null ?
                new ObjectParameter("CO_TIPO_DREL", cO_TIPO_DREL) :
                new ObjectParameter("CO_TIPO_DREL", typeof(string));
    
            var fE_EMIS_DRELParameter = fE_EMIS_DREL.HasValue ?
                new ObjectParameter("FE_EMIS_DREL", fE_EMIS_DREL) :
                new ObjectParameter("FE_EMIS_DREL", typeof(System.DateTime));
    
            var nU_DIGVParameter = nU_DIGV.HasValue ?
                new ObjectParameter("NU_DIGV", nU_DIGV) :
                new ObjectParameter("NU_DIGV", typeof(decimal));
    
            var cO_IDEN_DIGVParameter = cO_IDEN_DIGV != null ?
                new ObjectParameter("CO_IDEN_DIGV", cO_IDEN_DIGV) :
                new ObjectParameter("CO_IDEN_DIGV", typeof(string));
    
            var dE_DIGVParameter = dE_DIGV != null ?
                new ObjectParameter("DE_DIGV", dE_DIGV) :
                new ObjectParameter("DE_DIGV", typeof(string));
    
            var cO_TIPO_DIGVParameter = cO_TIPO_DIGV != null ?
                new ObjectParameter("CO_TIPO_DIGV", cO_TIPO_DIGV) :
                new ObjectParameter("CO_TIPO_DIGV", typeof(string));
    
            var nU_DISCParameter = nU_DISC.HasValue ?
                new ObjectParameter("NU_DISC", nU_DISC) :
                new ObjectParameter("NU_DISC", typeof(decimal));
    
            var cO_IDEN_DISCParameter = cO_IDEN_DISC != null ?
                new ObjectParameter("CO_IDEN_DISC", cO_IDEN_DISC) :
                new ObjectParameter("CO_IDEN_DISC", typeof(string));
    
            var dE_IDEN_DISCParameter = dE_IDEN_DISC != null ?
                new ObjectParameter("DE_IDEN_DISC", dE_IDEN_DISC) :
                new ObjectParameter("DE_IDEN_DISC", typeof(string));
    
            var cO_TIPO_DISCParameter = cO_TIPO_DISC != null ?
                new ObjectParameter("CO_TIPO_DISC", cO_TIPO_DISC) :
                new ObjectParameter("CO_TIPO_DISC", typeof(string));
    
            var nU_TOTA_TRIBParameter = nU_TOTA_TRIB.HasValue ?
                new ObjectParameter("NU_TOTA_TRIB", nU_TOTA_TRIB) :
                new ObjectParameter("NU_TOTA_TRIB", typeof(decimal));
    
            var cO_TRIBParameter = cO_TRIB != null ?
                new ObjectParameter("CO_TRIB", cO_TRIB) :
                new ObjectParameter("CO_TRIB", typeof(string));
    
            var dE_TRIBParameter = dE_TRIB != null ?
                new ObjectParameter("DE_TRIB", dE_TRIB) :
                new ObjectParameter("DE_TRIB", typeof(string));
    
            var cO_TIPO_TRIBParameter = cO_TIPO_TRIB != null ?
                new ObjectParameter("CO_TIPO_TRIB", cO_TIPO_TRIB) :
                new ObjectParameter("CO_TIPO_TRIB", typeof(string));
    
            var nU_TOTA_CARGParameter = nU_TOTA_CARG.HasValue ?
                new ObjectParameter("NU_TOTA_CARG", nU_TOTA_CARG) :
                new ObjectParameter("NU_TOTA_CARG", typeof(decimal));
    
            var tI_SOTR_CARGParameter = tI_SOTR_CARG != null ?
                new ObjectParameter("TI_SOTR_CARG", tI_SOTR_CARG) :
                new ObjectParameter("TI_SOTR_CARG", typeof(string));
    
            var cO_OPER_GRABParameter = cO_OPER_GRAB != null ?
                new ObjectParameter("CO_OPER_GRAB", cO_OPER_GRAB) :
                new ObjectParameter("CO_OPER_GRAB", typeof(string));
    
            var nU_OPER_GRABParameter = nU_OPER_GRAB.HasValue ?
                new ObjectParameter("NU_OPER_GRAB", nU_OPER_GRAB) :
                new ObjectParameter("NU_OPER_GRAB", typeof(decimal));
    
            var cO_OPER_INAFParameter = cO_OPER_INAF != null ?
                new ObjectParameter("CO_OPER_INAF", cO_OPER_INAF) :
                new ObjectParameter("CO_OPER_INAF", typeof(string));
    
            var nU_OPER_INAFParameter = nU_OPER_INAF.HasValue ?
                new ObjectParameter("NU_OPER_INAF", nU_OPER_INAF) :
                new ObjectParameter("NU_OPER_INAF", typeof(decimal));
    
            var cO_OPER_EXONParameter = cO_OPER_EXON != null ?
                new ObjectParameter("CO_OPER_EXON", cO_OPER_EXON) :
                new ObjectParameter("CO_OPER_EXON", typeof(string));
    
            var nU_OPER_EXONParameter = nU_OPER_EXON.HasValue ?
                new ObjectParameter("NU_OPER_EXON", nU_OPER_EXON) :
                new ObjectParameter("NU_OPER_EXON", typeof(decimal));
    
            var nU_TOTAParameter = nU_TOTA.HasValue ?
                new ObjectParameter("NU_TOTA", nU_TOTA) :
                new ObjectParameter("NU_TOTA", typeof(decimal));
    
            var cO_ESTA_ITEMParameter = cO_ESTA_ITEM != null ?
                new ObjectParameter("CO_ESTA_ITEM", cO_ESTA_ITEM) :
                new ObjectParameter("CO_ESTA_ITEM", typeof(string));
    
            var cO_OPER_GRATParameter = cO_OPER_GRAT != null ?
                new ObjectParameter("CO_OPER_GRAT", cO_OPER_GRAT) :
                new ObjectParameter("CO_OPER_GRAT", typeof(string));
    
            var nU_OPER_GRATParameter = nU_OPER_GRAT.HasValue ?
                new ObjectParameter("NU_OPER_GRAT", nU_OPER_GRAT) :
                new ObjectParameter("NU_OPER_GRAT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_TD_DOCU_SUNA_001", cO_IDENParameter, nU_RUCSParameter, dE_EMPRParameter, dE_DIREParameter, dE_DPTOParameter, dE_PROVParameter, dE_DISTParameter, cO_IDEN_DESTParameter, nU_RUCS_DESTParameter, fE_EMISParameter, dE_MOTI_BAJAParameter, cO_TIPO_DOCUParameter, cO_SERIParameter, nU_CORRParameter, cO_MONEParameter, cO_ESTAParameter, cO_VERS_UBLParameter, cO_VERS_ESTRParameter, nU_ORDEParameter, nU_SERI_DMODParameter, nU_CORR_DMODParameter, cO_TIPO_DMODParameter, cO_SERI_DRELParameter, nU_CORR_DRELParameter, nU_CORR_FINAParameter, cO_TIPO_DRELParameter, fE_EMIS_DRELParameter, nU_DIGVParameter, cO_IDEN_DIGVParameter, dE_DIGVParameter, cO_TIPO_DIGVParameter, nU_DISCParameter, cO_IDEN_DISCParameter, dE_IDEN_DISCParameter, cO_TIPO_DISCParameter, nU_TOTA_TRIBParameter, cO_TRIBParameter, dE_TRIBParameter, cO_TIPO_TRIBParameter, nU_TOTA_CARGParameter, tI_SOTR_CARGParameter, cO_OPER_GRABParameter, nU_OPER_GRABParameter, cO_OPER_INAFParameter, nU_OPER_INAFParameter, cO_OPER_EXONParameter, nU_OPER_EXONParameter, nU_TOTAParameter, cO_ESTA_ITEMParameter, cO_OPER_GRATParameter, nU_OPER_GRATParameter);
        }
    
        public virtual ObjectResult<USP_SEL_BUSQUEDA_001_Result> USP_SEL_BUSQUEDA_001(string cO_ESTA, string nU_RUCS, string nU_RUCS_DEST, Nullable<System.DateTime> fE_EMIS_INIC, Nullable<System.DateTime> fE_EMIS_FINA)
        {
            var cO_ESTAParameter = cO_ESTA != null ?
                new ObjectParameter("CO_ESTA", cO_ESTA) :
                new ObjectParameter("CO_ESTA", typeof(string));
    
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var nU_RUCS_DESTParameter = nU_RUCS_DEST != null ?
                new ObjectParameter("NU_RUCS_DEST", nU_RUCS_DEST) :
                new ObjectParameter("NU_RUCS_DEST", typeof(string));
    
            var fE_EMIS_INICParameter = fE_EMIS_INIC.HasValue ?
                new ObjectParameter("FE_EMIS_INIC", fE_EMIS_INIC) :
                new ObjectParameter("FE_EMIS_INIC", typeof(System.DateTime));
    
            var fE_EMIS_FINAParameter = fE_EMIS_FINA.HasValue ?
                new ObjectParameter("FE_EMIS_FINA", fE_EMIS_FINA) :
                new ObjectParameter("FE_EMIS_FINA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_BUSQUEDA_001_Result>("USP_SEL_BUSQUEDA_001", cO_ESTAParameter, nU_RUCSParameter, nU_RUCS_DESTParameter, fE_EMIS_INICParameter, fE_EMIS_FINAParameter);
        }
    
        public virtual ObjectResult<USP_SEL_COMP_RETE_001_Result> USP_SEL_COMP_RETE_001(string nU_RUCS, string cO_SERI, string nU_CORR, string cO_TIPO_DOCU)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_COMP_RETE_001_Result>("USP_SEL_COMP_RETE_001", nU_RUCSParameter, cO_SERIParameter, nU_CORRParameter, cO_TIPO_DOCUParameter);
        }
    
        public virtual ObjectResult<USP_SEL_COMP_RETE_002_Result> USP_SEL_COMP_RETE_002(string nU_RUCS, string cO_SERI, string nU_CORR, string cO_TIPO_DOCU)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_COMP_RETE_002_Result>("USP_SEL_COMP_RETE_002", nU_RUCSParameter, cO_SERIParameter, nU_CORRParameter, cO_TIPO_DOCUParameter);
        }
    
        public virtual ObjectResult<USP_SEL_COMP_RETE_003_Result> USP_SEL_COMP_RETE_003(string nU_RUCS, string cO_SERI, string nU_CORR, string cO_TIPO_DOCU)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_COMP_RETE_003_Result>("USP_SEL_COMP_RETE_003", nU_RUCSParameter, cO_SERIParameter, nU_CORRParameter, cO_TIPO_DOCUParameter);
        }
    
        public virtual ObjectResult<USP_SEL_COMP_RETE_004_Result> USP_SEL_COMP_RETE_004(string nU_RUCS, string cO_SERI, string nU_CORR, string cO_TIPO_DOCU)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_COMP_RETE_004_Result>("USP_SEL_COMP_RETE_004", nU_RUCSParameter, cO_SERIParameter, nU_CORRParameter, cO_TIPO_DOCUParameter);
        }
    
        public virtual ObjectResult<USP_SEL_COMP_RETE_005_Result> USP_SEL_COMP_RETE_005()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_COMP_RETE_005_Result>("USP_SEL_COMP_RETE_005");
        }
    
        public virtual ObjectResult<USP_SEL_FACTURA_001_Result> USP_SEL_FACTURA_001(string cO_ESTA, string vOPC)
        {
            var cO_ESTAParameter = cO_ESTA != null ?
                new ObjectParameter("CO_ESTA", cO_ESTA) :
                new ObjectParameter("CO_ESTA", typeof(string));
    
            var vOPCParameter = vOPC != null ?
                new ObjectParameter("VOPC", vOPC) :
                new ObjectParameter("VOPC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_FACTURA_001_Result>("USP_SEL_FACTURA_001", cO_ESTAParameter, vOPCParameter);
        }
    
        public virtual ObjectResult<USP_SEL_FACTURA_002_Result> USP_SEL_FACTURA_002(string nU_RUCS, string cO_SERI, string nU_CORR, string cO_TIPO_DOCU)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_FACTURA_002_Result>("USP_SEL_FACTURA_002", nU_RUCSParameter, cO_SERIParameter, nU_CORRParameter, cO_TIPO_DOCUParameter);
        }
    
        public virtual ObjectResult<USP_SEL_FACTURA_003_Result> USP_SEL_FACTURA_003(string nU_RUCS, string cO_SERI, string nU_CORR, string cO_TIPO_DOCU)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_FACTURA_003_Result>("USP_SEL_FACTURA_003", nU_RUCSParameter, cO_SERIParameter, nU_CORRParameter, cO_TIPO_DOCUParameter);
        }
    
        public virtual int USP_SEL_FACTURA_004(string nU_RUCS, string cO_TIPO_DOCU, string cO_SERI, string nU_CORR, string dE_OBSE, string cO_ESTA)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var dE_OBSEParameter = dE_OBSE != null ?
                new ObjectParameter("DE_OBSE", dE_OBSE) :
                new ObjectParameter("DE_OBSE", typeof(string));
    
            var cO_ESTAParameter = cO_ESTA != null ?
                new ObjectParameter("CO_ESTA", cO_ESTA) :
                new ObjectParameter("CO_ESTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SEL_FACTURA_004", nU_RUCSParameter, cO_TIPO_DOCUParameter, cO_SERIParameter, nU_CORRParameter, dE_OBSEParameter, cO_ESTAParameter);
        }
    
        public virtual ObjectResult<USP_SEL_FACTURA_005_Result> USP_SEL_FACTURA_005()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_FACTURA_005_Result>("USP_SEL_FACTURA_005");
        }
    
        public virtual ObjectResult<USP_SEL_FACTURA_006_Result> USP_SEL_FACTURA_006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_FACTURA_006_Result>("USP_SEL_FACTURA_006");
        }
    
        public virtual ObjectResult<USP_SEL_LISTA_BUSQUEDA_001_Result> USP_SEL_LISTA_BUSQUEDA_001(string oPC)
        {
            var oPCParameter = oPC != null ?
                new ObjectParameter("OPC", oPC) :
                new ObjectParameter("OPC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_LISTA_BUSQUEDA_001_Result>("USP_SEL_LISTA_BUSQUEDA_001", oPCParameter);
        }
    
        public virtual ObjectResult<USP_SEL_M_DOCU_MASI_002_Result> USP_SEL_M_DOCU_MASI_002(string nU_RUCS, string cO_SERI, string nU_CORR, string cO_TIPO_DOCU)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_M_DOCU_MASI_002_Result>("USP_SEL_M_DOCU_MASI_002", nU_RUCSParameter, cO_SERIParameter, nU_CORRParameter, cO_TIPO_DOCUParameter);
        }
    
        public virtual ObjectResult<USP_SEL_M_DOCU_MASI_003_Result> USP_SEL_M_DOCU_MASI_003(string nU_RUCS, string cO_SERI, string nU_CORR, string cO_TIPO_DOCU)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_M_DOCU_MASI_003_Result>("USP_SEL_M_DOCU_MASI_003", nU_RUCSParameter, cO_SERIParameter, nU_CORRParameter, cO_TIPO_DOCUParameter);
        }
    
        public virtual ObjectResult<USP_SEL_TD_DOCU_RETE_001_Result> USP_SEL_TD_DOCU_RETE_001()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_TD_DOCU_RETE_001_Result>("USP_SEL_TD_DOCU_RETE_001");
        }
    
        public virtual ObjectResult<USP_SEL_TD_DOCU_RETE_002_Result> USP_SEL_TD_DOCU_RETE_002(string cO_ESTA, string nU_RUCS, string nU_RUCS_DEST, Nullable<System.DateTime> fE_EMIS_INIC, Nullable<System.DateTime> fE_EMIS_FINA)
        {
            var cO_ESTAParameter = cO_ESTA != null ?
                new ObjectParameter("CO_ESTA", cO_ESTA) :
                new ObjectParameter("CO_ESTA", typeof(string));
    
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var nU_RUCS_DESTParameter = nU_RUCS_DEST != null ?
                new ObjectParameter("NU_RUCS_DEST", nU_RUCS_DEST) :
                new ObjectParameter("NU_RUCS_DEST", typeof(string));
    
            var fE_EMIS_INICParameter = fE_EMIS_INIC.HasValue ?
                new ObjectParameter("FE_EMIS_INIC", fE_EMIS_INIC) :
                new ObjectParameter("FE_EMIS_INIC", typeof(System.DateTime));
    
            var fE_EMIS_FINAParameter = fE_EMIS_FINA.HasValue ?
                new ObjectParameter("FE_EMIS_FINA", fE_EMIS_FINA) :
                new ObjectParameter("FE_EMIS_FINA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_TD_DOCU_RETE_002_Result>("USP_SEL_TD_DOCU_RETE_002", cO_ESTAParameter, nU_RUCSParameter, nU_RUCS_DESTParameter, fE_EMIS_INICParameter, fE_EMIS_FINAParameter);
        }
    
        public virtual ObjectResult<USP_SEL_TD_DOCU_SUNA_001_Result> USP_SEL_TD_DOCU_SUNA_001(string nU_RUCS, string cO_TIPO_DOCU, string cO_SERI, string nU_CORR, Nullable<System.DateTime> fE_EMIS, Nullable<decimal> nU_IMPO_TOTA)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var fE_EMISParameter = fE_EMIS.HasValue ?
                new ObjectParameter("FE_EMIS", fE_EMIS) :
                new ObjectParameter("FE_EMIS", typeof(System.DateTime));
    
            var nU_IMPO_TOTAParameter = nU_IMPO_TOTA.HasValue ?
                new ObjectParameter("NU_IMPO_TOTA", nU_IMPO_TOTA) :
                new ObjectParameter("NU_IMPO_TOTA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_TD_DOCU_SUNA_001_Result>("USP_SEL_TD_DOCU_SUNA_001", nU_RUCSParameter, cO_TIPO_DOCUParameter, cO_SERIParameter, nU_CORRParameter, fE_EMISParameter, nU_IMPO_TOTAParameter);
        }
    
        public virtual ObjectResult<USP_SEL_TD_DOCU_SUNA_009_Result> USP_SEL_TD_DOCU_SUNA_009()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_TD_DOCU_SUNA_009_Result>("USP_SEL_TD_DOCU_SUNA_009");
        }
    
        public virtual ObjectResult<USP_SEL_VW_TIPO_DOCU_001_Result> USP_SEL_VW_TIPO_DOCU_001()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_VW_TIPO_DOCU_001_Result>("USP_SEL_VW_TIPO_DOCU_001");
        }
    
        public virtual ObjectResult<USP_SEL_vwM_EMPR_RETE_001_Result> USP_SEL_vwM_EMPR_RETE_001()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_vwM_EMPR_RETE_001_Result>("USP_SEL_vwM_EMPR_RETE_001");
        }
    
        public virtual int USP_UPD_TD_DOCU_RETE_001(string nU_RUCS, string cO_TIPO_DOCU, string cO_SERI, string nU_CORR, string cO_ESTA, string dE_OBSE)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_ESTAParameter = cO_ESTA != null ?
                new ObjectParameter("CO_ESTA", cO_ESTA) :
                new ObjectParameter("CO_ESTA", typeof(string));
    
            var dE_OBSEParameter = dE_OBSE != null ?
                new ObjectParameter("DE_OBSE", dE_OBSE) :
                new ObjectParameter("DE_OBSE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_TD_DOCU_RETE_001", nU_RUCSParameter, cO_TIPO_DOCUParameter, cO_SERIParameter, nU_CORRParameter, cO_ESTAParameter, dE_OBSEParameter);
        }
    
        public virtual int USP_UPD_TD_DOCU_SUNA_001(string nU_RUCS, string cO_TIPO_DOCU, string cO_SERI, string nU_CORR)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_TD_DOCU_SUNA_001", nU_RUCSParameter, cO_TIPO_DOCUParameter, cO_SERIParameter, nU_CORRParameter);
        }
    
        public virtual int USP_UPD_TD_DOCU_SUNA_002(string nU_RUCS, string cO_TIPO_DOCU, string cO_SERI, string nU_CORR, string cO_ESTA, string dE_OBSE)
        {
            var nU_RUCSParameter = nU_RUCS != null ?
                new ObjectParameter("NU_RUCS", nU_RUCS) :
                new ObjectParameter("NU_RUCS", typeof(string));
    
            var cO_TIPO_DOCUParameter = cO_TIPO_DOCU != null ?
                new ObjectParameter("CO_TIPO_DOCU", cO_TIPO_DOCU) :
                new ObjectParameter("CO_TIPO_DOCU", typeof(string));
    
            var cO_SERIParameter = cO_SERI != null ?
                new ObjectParameter("CO_SERI", cO_SERI) :
                new ObjectParameter("CO_SERI", typeof(string));
    
            var nU_CORRParameter = nU_CORR != null ?
                new ObjectParameter("NU_CORR", nU_CORR) :
                new ObjectParameter("NU_CORR", typeof(string));
    
            var cO_ESTAParameter = cO_ESTA != null ?
                new ObjectParameter("CO_ESTA", cO_ESTA) :
                new ObjectParameter("CO_ESTA", typeof(string));
    
            var dE_OBSEParameter = dE_OBSE != null ?
                new ObjectParameter("DE_OBSE", dE_OBSE) :
                new ObjectParameter("DE_OBSE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_TD_DOCU_SUNA_002", nU_RUCSParameter, cO_TIPO_DOCUParameter, cO_SERIParameter, nU_CORRParameter, cO_ESTAParameter, dE_OBSEParameter);
        }
    }
}
