//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SICER_WEBEntities1 : DbContext
    {
        public SICER_WEBEntities1()
            : base("name=SICER_WEBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<DocumentoWeb> DocumentoWeb { get; set; }
        public virtual DbSet<DocumentoWebAuditoria> DocumentoWebAuditoria { get; set; }
        public virtual DbSet<DocumentoWebRendicion> DocumentoWebRendicion { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EmpresasSICER> EmpresasSICER { get; set; }
        public virtual DbSet<MetodoPago> MetodoPago { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Acceso> Acceso { get; set; }
        public virtual DbSet<Aprobacion> Aprobacion { get; set; }
        public virtual DbSet<Concepto> Concepto { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<NivelAprobacion> NivelAprobacion { get; set; }
        public virtual DbSet<PerfilUsuario> PerfilUsuario { get; set; }
        public virtual DbSet<UsuarioAreaNivel> UsuarioAreaNivel { get; set; }
    
        public virtual ObjectResult<string> MSS_SP_SICER_GETACCOUNTFROMCONFIG(string u_Documento, string u_codigo)
        {
            var u_DocumentoParameter = u_Documento != null ?
                new ObjectParameter("U_Documento", u_Documento) :
                new ObjectParameter("U_Documento", typeof(string));
    
            var u_codigoParameter = u_codigo != null ?
                new ObjectParameter("U_codigo", u_codigo) :
                new ObjectParameter("U_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MSS_SP_SICER_GETACCOUNTFROMCONFIG", u_DocumentoParameter, u_codigoParameter);
        }
    
        public virtual int MSS_WEB_AccesoInsertar(string idLog, Nullable<System.DateTime> fecha, string usuario, string contraseña, string operacion)
        {
            var idLogParameter = idLog != null ?
                new ObjectParameter("IdLog", idLog) :
                new ObjectParameter("IdLog", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var operacionParameter = operacion != null ?
                new ObjectParameter("Operacion", operacion) :
                new ObjectParameter("Operacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_AccesoInsertar", idLogParameter, fechaParameter, usuarioParameter, contraseñaParameter, operacionParameter);
        }
    
        public virtual int MSS_WEB_AreaObtener(Nullable<int> idArea)
        {
            var idAreaParameter = idArea.HasValue ?
                new ObjectParameter("IdArea", idArea) :
                new ObjectParameter("IdArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_AreaObtener", idAreaParameter);
        }
    
        public virtual int MSS_WEB_BancoListar(Nullable<int> id, Nullable<int> tipo, Nullable<int> tipo2)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var tipo2Parameter = tipo2.HasValue ?
                new ObjectParameter("Tipo2", tipo2) :
                new ObjectParameter("Tipo2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_BancoListar", idParameter, tipoParameter, tipo2Parameter);
        }
    
        public virtual int MSS_WEB_BancoObtener(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_BancoObtener", idParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_CentroCostosListar_Result> MSS_WEB_CentroCostosListar(Nullable<int> idEmpresa, Nullable<int> nivel)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var nivelParameter = nivel.HasValue ?
                new ObjectParameter("Nivel", nivel) :
                new ObjectParameter("Nivel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_CentroCostosListar_Result>("MSS_WEB_CentroCostosListar", idEmpresaParameter, nivelParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_CentroCostosObtener_Result> MSS_WEB_CentroCostosObtener(string ocrCode)
        {
            var ocrCodeParameter = ocrCode != null ?
                new ObjectParameter("OcrCode", ocrCode) :
                new ObjectParameter("OcrCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_CentroCostosObtener_Result>("MSS_WEB_CentroCostosObtener", ocrCodeParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_ConceptoListar_Result> MSS_WEB_ConceptoListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_ConceptoListar_Result>("MSS_WEB_ConceptoListar");
        }
    
        public virtual ObjectResult<MSS_WEB_ConceptoObtener_Result> MSS_WEB_ConceptoObtener(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_ConceptoObtener_Result>("MSS_WEB_ConceptoObtener", codigoParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_CuentaContableDevolucionObtener_Result> MSS_WEB_CuentaContableDevolucionObtener(string u_Codigo)
        {
            var u_CodigoParameter = u_Codigo != null ?
                new ObjectParameter("U_Codigo", u_Codigo) :
                new ObjectParameter("U_Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_CuentaContableDevolucionObtener_Result>("MSS_WEB_CuentaContableDevolucionObtener", u_CodigoParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_CuentasContablesDevolucionListar_Result> MSS_WEB_CuentasContablesDevolucionListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_CuentasContablesDevolucionListar_Result>("MSS_WEB_CuentasContablesDevolucionListar");
        }
    
        public virtual ObjectResult<MSS_WEB_DocumentoListar_Result> MSS_WEB_DocumentoListar(Nullable<int> id, Nullable<int> tipo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_DocumentoListar_Result>("MSS_WEB_DocumentoListar", idParameter, tipoParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_DocumentoObtener_Result> MSS_WEB_DocumentoObtener(Nullable<int> idDocumento)
        {
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("IdDocumento", idDocumento) :
                new ObjectParameter("IdDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_DocumentoObtener_Result>("MSS_WEB_DocumentoObtener", idDocumentoParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_EmpresaListar_Result> MSS_WEB_EmpresaListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_EmpresaListar_Result>("MSS_WEB_EmpresaListar");
        }
    
        public virtual ObjectResult<MSS_WEB_EmpresaObtener_Result> MSS_WEB_EmpresaObtener(Nullable<int> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_EmpresaObtener_Result>("MSS_WEB_EmpresaObtener", idEmpresaParameter);
        }
    
        public virtual ObjectResult<Nullable<short>> MSS_WEB_GETSERIES(string prefix)
        {
            var prefixParameter = prefix != null ?
                new ObjectParameter("Prefix", prefix) :
                new ObjectParameter("Prefix", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<short>>("MSS_WEB_GETSERIES", prefixParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_MetodoPagoListar_Result> MSS_WEB_MetodoPagoListar(Nullable<int> id, Nullable<int> tipo, Nullable<int> tipo2)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var tipo2Parameter = tipo2.HasValue ?
                new ObjectParameter("Tipo2", tipo2) :
                new ObjectParameter("Tipo2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_MetodoPagoListar_Result>("MSS_WEB_MetodoPagoListar", idParameter, tipoParameter, tipo2Parameter);
        }
    
        public virtual ObjectResult<MSS_WEB_MetodoPagoObtener_Result> MSS_WEB_MetodoPagoObtener(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_MetodoPagoObtener_Result>("MSS_WEB_MetodoPagoObtener", idParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_MonedaListar_Result> MSS_WEB_MonedaListar(Nullable<int> idDocumentoWeb)
        {
            var idDocumentoWebParameter = idDocumentoWeb.HasValue ?
                new ObjectParameter("IdDocumentoWeb", idDocumentoWeb) :
                new ObjectParameter("IdDocumentoWeb", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_MonedaListar_Result>("MSS_WEB_MonedaListar", idDocumentoWebParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_MonedaObtener_Result> MSS_WEB_MonedaObtener(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_MonedaObtener_Result>("MSS_WEB_MonedaObtener", idParameter);
        }
    
        public virtual int MSS_WEB_NivelAprobacionInsertar(string descripcion, string nivel, string documento, string esDeMonto, string monto, string userCreate, Nullable<System.DateTime> createDate, string userUpdate, Nullable<System.DateTime> updateDate)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var nivelParameter = nivel != null ?
                new ObjectParameter("Nivel", nivel) :
                new ObjectParameter("Nivel", typeof(string));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(string));
    
            var esDeMontoParameter = esDeMonto != null ?
                new ObjectParameter("EsDeMonto", esDeMonto) :
                new ObjectParameter("EsDeMonto", typeof(string));
    
            var montoParameter = monto != null ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(string));
    
            var userCreateParameter = userCreate != null ?
                new ObjectParameter("UserCreate", userCreate) :
                new ObjectParameter("UserCreate", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var userUpdateParameter = userUpdate != null ?
                new ObjectParameter("UserUpdate", userUpdate) :
                new ObjectParameter("UserUpdate", typeof(string));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_NivelAprobacionInsertar", descripcionParameter, nivelParameter, documentoParameter, esDeMontoParameter, montoParameter, userCreateParameter, createDateParameter, userUpdateParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_NivelAprobacionListar_Result> MSS_WEB_NivelAprobacionListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_NivelAprobacionListar_Result>("MSS_WEB_NivelAprobacionListar");
        }
    
        public virtual int MSS_WEB_NivelAprobacionModificar(Nullable<int> idNivel, string descripcion, string nivel, string documento, string esDeMonto, string monto, string userCreate, Nullable<System.DateTime> createDate, string userUpdate, Nullable<System.DateTime> updateDate)
        {
            var idNivelParameter = idNivel.HasValue ?
                new ObjectParameter("IdNivel", idNivel) :
                new ObjectParameter("IdNivel", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var nivelParameter = nivel != null ?
                new ObjectParameter("Nivel", nivel) :
                new ObjectParameter("Nivel", typeof(string));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(string));
    
            var esDeMontoParameter = esDeMonto != null ?
                new ObjectParameter("EsDeMonto", esDeMonto) :
                new ObjectParameter("EsDeMonto", typeof(string));
    
            var montoParameter = monto != null ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(string));
    
            var userCreateParameter = userCreate != null ?
                new ObjectParameter("UserCreate", userCreate) :
                new ObjectParameter("UserCreate", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var userUpdateParameter = userUpdate != null ?
                new ObjectParameter("UserUpdate", userUpdate) :
                new ObjectParameter("UserUpdate", typeof(string));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_NivelAprobacionModificar", idNivelParameter, descripcionParameter, nivelParameter, documentoParameter, esDeMontoParameter, montoParameter, userCreateParameter, createDateParameter, userUpdateParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_NivelAprobacionObtener_Result> MSS_WEB_NivelAprobacionObtener(Nullable<int> idNivel, Nullable<int> tipo)
        {
            var idNivelParameter = idNivel.HasValue ?
                new ObjectParameter("IdNivel", idNivel) :
                new ObjectParameter("IdNivel", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_NivelAprobacionObtener_Result>("MSS_WEB_NivelAprobacionObtener", idNivelParameter, tipoParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_NivelAprobacionObtenerV2_Result> MSS_WEB_NivelAprobacionObtenerV2(Nullable<int> idTipoDocumento, Nullable<int> idNivelMoneda)
        {
            var idTipoDocumentoParameter = idTipoDocumento.HasValue ?
                new ObjectParameter("idTipoDocumento", idTipoDocumento) :
                new ObjectParameter("idTipoDocumento", typeof(int));
    
            var idNivelMonedaParameter = idNivelMoneda.HasValue ?
                new ObjectParameter("idNivelMoneda", idNivelMoneda) :
                new ObjectParameter("idNivelMoneda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_NivelAprobacionObtenerV2_Result>("MSS_WEB_NivelAprobacionObtenerV2", idTipoDocumentoParameter, idNivelMonedaParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_NivelSeguridadContraseña_Result> MSS_WEB_NivelSeguridadContraseña(string pass, string usuario, Nullable<int> numNumericos, Nullable<int> numMayusculas, Nullable<int> numEspeciales)
        {
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var numNumericosParameter = numNumericos.HasValue ?
                new ObjectParameter("NumNumericos", numNumericos) :
                new ObjectParameter("NumNumericos", typeof(int));
    
            var numMayusculasParameter = numMayusculas.HasValue ?
                new ObjectParameter("NumMayusculas", numMayusculas) :
                new ObjectParameter("NumMayusculas", typeof(int));
    
            var numEspecialesParameter = numEspeciales.HasValue ?
                new ObjectParameter("NumEspeciales", numEspeciales) :
                new ObjectParameter("NumEspeciales", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_NivelSeguridadContraseña_Result>("MSS_WEB_NivelSeguridadContraseña", passParameter, usuarioParameter, numNumericosParameter, numMayusculasParameter, numEspecialesParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_PARTIDAPRESUPUESTAL_GET_Result> MSS_WEB_PARTIDAPRESUPUESTAL_GET(string u_MSSP_NIV)
        {
            var u_MSSP_NIVParameter = u_MSSP_NIV != null ?
                new ObjectParameter("U_MSSP_NIV", u_MSSP_NIV) :
                new ObjectParameter("U_MSSP_NIV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_PARTIDAPRESUPUESTAL_GET_Result>("MSS_WEB_PARTIDAPRESUPUESTAL_GET", u_MSSP_NIVParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_PARTIDAPRESUPUESTAL_GETLIST_Result> MSS_WEB_PARTIDAPRESUPUESTAL_GETLIST(string codigoCentroCostos)
        {
            var codigoCentroCostosParameter = codigoCentroCostos != null ?
                new ObjectParameter("CodigoCentroCostos", codigoCentroCostos) :
                new ObjectParameter("CodigoCentroCostos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_PARTIDAPRESUPUESTAL_GETLIST_Result>("MSS_WEB_PARTIDAPRESUPUESTAL_GETLIST", codigoCentroCostosParameter);
        }
    
        public virtual int MSS_WEB_PerfilUsuarioInsertar(string descripcion, string modAdministrador, string tipoAprobador, string modCajaChica, string modEntregaRendir, string modReembolso, string creaCajaChica, string creaEntregaRendir, string creaReembolso, string userCreate, Nullable<System.DateTime> createDate, string userUpdate, Nullable<System.DateTime> updateDate)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var modAdministradorParameter = modAdministrador != null ?
                new ObjectParameter("ModAdministrador", modAdministrador) :
                new ObjectParameter("ModAdministrador", typeof(string));
    
            var tipoAprobadorParameter = tipoAprobador != null ?
                new ObjectParameter("TipoAprobador", tipoAprobador) :
                new ObjectParameter("TipoAprobador", typeof(string));
    
            var modCajaChicaParameter = modCajaChica != null ?
                new ObjectParameter("ModCajaChica", modCajaChica) :
                new ObjectParameter("ModCajaChica", typeof(string));
    
            var modEntregaRendirParameter = modEntregaRendir != null ?
                new ObjectParameter("ModEntregaRendir", modEntregaRendir) :
                new ObjectParameter("ModEntregaRendir", typeof(string));
    
            var modReembolsoParameter = modReembolso != null ?
                new ObjectParameter("ModReembolso", modReembolso) :
                new ObjectParameter("ModReembolso", typeof(string));
    
            var creaCajaChicaParameter = creaCajaChica != null ?
                new ObjectParameter("CreaCajaChica", creaCajaChica) :
                new ObjectParameter("CreaCajaChica", typeof(string));
    
            var creaEntregaRendirParameter = creaEntregaRendir != null ?
                new ObjectParameter("CreaEntregaRendir", creaEntregaRendir) :
                new ObjectParameter("CreaEntregaRendir", typeof(string));
    
            var creaReembolsoParameter = creaReembolso != null ?
                new ObjectParameter("CreaReembolso", creaReembolso) :
                new ObjectParameter("CreaReembolso", typeof(string));
    
            var userCreateParameter = userCreate != null ?
                new ObjectParameter("UserCreate", userCreate) :
                new ObjectParameter("UserCreate", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var userUpdateParameter = userUpdate != null ?
                new ObjectParameter("UserUpdate", userUpdate) :
                new ObjectParameter("UserUpdate", typeof(string));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_PerfilUsuarioInsertar", descripcionParameter, modAdministradorParameter, tipoAprobadorParameter, modCajaChicaParameter, modEntregaRendirParameter, modReembolsoParameter, creaCajaChicaParameter, creaEntregaRendirParameter, creaReembolsoParameter, userCreateParameter, createDateParameter, userUpdateParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_PerfilUsuarioListar_Result> MSS_WEB_PerfilUsuarioListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_PerfilUsuarioListar_Result>("MSS_WEB_PerfilUsuarioListar");
        }
    
        public virtual int MSS_WEB_PerfilUsuarioModificar(Nullable<int> idPerfilUsuario, string descripcion, string modAdministrador, string tipoAprobador, string modCajaChica, string modEntregaRendir, string modReembolso, string creaCajaChica, string creaEntregaRendir, string creaReembolso, string userCreate, Nullable<System.DateTime> createDate, string userUpdate, Nullable<System.DateTime> updateDate)
        {
            var idPerfilUsuarioParameter = idPerfilUsuario.HasValue ?
                new ObjectParameter("IdPerfilUsuario", idPerfilUsuario) :
                new ObjectParameter("IdPerfilUsuario", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var modAdministradorParameter = modAdministrador != null ?
                new ObjectParameter("ModAdministrador", modAdministrador) :
                new ObjectParameter("ModAdministrador", typeof(string));
    
            var tipoAprobadorParameter = tipoAprobador != null ?
                new ObjectParameter("TipoAprobador", tipoAprobador) :
                new ObjectParameter("TipoAprobador", typeof(string));
    
            var modCajaChicaParameter = modCajaChica != null ?
                new ObjectParameter("ModCajaChica", modCajaChica) :
                new ObjectParameter("ModCajaChica", typeof(string));
    
            var modEntregaRendirParameter = modEntregaRendir != null ?
                new ObjectParameter("ModEntregaRendir", modEntregaRendir) :
                new ObjectParameter("ModEntregaRendir", typeof(string));
    
            var modReembolsoParameter = modReembolso != null ?
                new ObjectParameter("ModReembolso", modReembolso) :
                new ObjectParameter("ModReembolso", typeof(string));
    
            var creaCajaChicaParameter = creaCajaChica != null ?
                new ObjectParameter("CreaCajaChica", creaCajaChica) :
                new ObjectParameter("CreaCajaChica", typeof(string));
    
            var creaEntregaRendirParameter = creaEntregaRendir != null ?
                new ObjectParameter("CreaEntregaRendir", creaEntregaRendir) :
                new ObjectParameter("CreaEntregaRendir", typeof(string));
    
            var creaReembolsoParameter = creaReembolso != null ?
                new ObjectParameter("CreaReembolso", creaReembolso) :
                new ObjectParameter("CreaReembolso", typeof(string));
    
            var userCreateParameter = userCreate != null ?
                new ObjectParameter("UserCreate", userCreate) :
                new ObjectParameter("UserCreate", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var userUpdateParameter = userUpdate != null ?
                new ObjectParameter("UserUpdate", userUpdate) :
                new ObjectParameter("UserUpdate", typeof(string));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_PerfilUsuarioModificar", idPerfilUsuarioParameter, descripcionParameter, modAdministradorParameter, tipoAprobadorParameter, modCajaChicaParameter, modEntregaRendirParameter, modReembolsoParameter, creaCajaChicaParameter, creaEntregaRendirParameter, creaReembolsoParameter, userCreateParameter, createDateParameter, userUpdateParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_PerfilUsuarioObtener_Result> MSS_WEB_PerfilUsuarioObtener(Nullable<int> idPerfilUsuario)
        {
            var idPerfilUsuarioParameter = idPerfilUsuario.HasValue ?
                new ObjectParameter("IdPerfilUsuario", idPerfilUsuario) :
                new ObjectParameter("IdPerfilUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_PerfilUsuarioObtener_Result>("MSS_WEB_PerfilUsuarioObtener", idPerfilUsuarioParameter);
        }
    
        public virtual int MSS_WEB_ProveedorInsertar(string cardCode, string cardName, string tipoDocumento, string documento, Nullable<int> proceso, Nullable<int> idProceso, Nullable<int> estado, string userCreate, Nullable<System.DateTime> createDate, string userUpdate, Nullable<System.DateTime> updateDate)
        {
            var cardCodeParameter = cardCode != null ?
                new ObjectParameter("CardCode", cardCode) :
                new ObjectParameter("CardCode", typeof(string));
    
            var cardNameParameter = cardName != null ?
                new ObjectParameter("CardName", cardName) :
                new ObjectParameter("CardName", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento != null ?
                new ObjectParameter("TipoDocumento", tipoDocumento) :
                new ObjectParameter("TipoDocumento", typeof(string));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(string));
    
            var procesoParameter = proceso.HasValue ?
                new ObjectParameter("Proceso", proceso) :
                new ObjectParameter("Proceso", typeof(int));
    
            var idProcesoParameter = idProceso.HasValue ?
                new ObjectParameter("IdProceso", idProceso) :
                new ObjectParameter("IdProceso", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var userCreateParameter = userCreate != null ?
                new ObjectParameter("UserCreate", userCreate) :
                new ObjectParameter("UserCreate", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var userUpdateParameter = userUpdate != null ?
                new ObjectParameter("UserUpdate", userUpdate) :
                new ObjectParameter("UserUpdate", typeof(string));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_ProveedorInsertar", cardCodeParameter, cardNameParameter, tipoDocumentoParameter, documentoParameter, procesoParameter, idProcesoParameter, estadoParameter, userCreateParameter, createDateParameter, userUpdateParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_ProveedorListar_Result> MSS_WEB_ProveedorListar(Nullable<int> id, Nullable<int> tipo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_ProveedorListar_Result>("MSS_WEB_ProveedorListar", idParameter, tipoParameter);
        }
    
        public virtual int MSS_WEB_ProveedorModificar(Nullable<int> idProveedor, string cardCode, string cardName, string tipoDocumento, string documento, Nullable<int> proceso, Nullable<int> idProceso, Nullable<int> estado, string userCreate, Nullable<System.DateTime> createDate, string userUpdate, Nullable<System.DateTime> updateDate)
        {
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("IdProveedor", idProveedor) :
                new ObjectParameter("IdProveedor", typeof(int));
    
            var cardCodeParameter = cardCode != null ?
                new ObjectParameter("CardCode", cardCode) :
                new ObjectParameter("CardCode", typeof(string));
    
            var cardNameParameter = cardName != null ?
                new ObjectParameter("CardName", cardName) :
                new ObjectParameter("CardName", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento != null ?
                new ObjectParameter("TipoDocumento", tipoDocumento) :
                new ObjectParameter("TipoDocumento", typeof(string));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(string));
    
            var procesoParameter = proceso.HasValue ?
                new ObjectParameter("Proceso", proceso) :
                new ObjectParameter("Proceso", typeof(int));
    
            var idProcesoParameter = idProceso.HasValue ?
                new ObjectParameter("IdProceso", idProceso) :
                new ObjectParameter("IdProceso", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var userCreateParameter = userCreate != null ?
                new ObjectParameter("UserCreate", userCreate) :
                new ObjectParameter("UserCreate", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var userUpdateParameter = userUpdate != null ?
                new ObjectParameter("UserUpdate", userUpdate) :
                new ObjectParameter("UserUpdate", typeof(string));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_ProveedorModificar", idProveedorParameter, cardCodeParameter, cardNameParameter, tipoDocumentoParameter, documentoParameter, procesoParameter, idProcesoParameter, estadoParameter, userCreateParameter, createDateParameter, userUpdateParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_ProveedorObtener_Result> MSS_WEB_ProveedorObtener(Nullable<int> id, Nullable<int> tipo, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_ProveedorObtener_Result>("MSS_WEB_ProveedorObtener", idParameter, tipoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> MSS_WEB_TIPOCAMBIO_GET(string currency)
        {
            var currencyParameter = currency != null ?
                new ObjectParameter("Currency", currency) :
                new ObjectParameter("Currency", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("MSS_WEB_TIPOCAMBIO_GET", currencyParameter);
        }
    
        public virtual int MSS_WEB_UsuarioEliminar(Nullable<int> tipo, Nullable<int> idUsuario)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_UsuarioEliminar", tipoParameter, idUsuarioParameter);
        }
    
        public virtual int MSS_WEB_UsuarioInsertar(string cardCode, string pass, string cardName, string tipo, string phone, string mail, string cantMaxCC, string cantMaxER, string cantMaxRE, Nullable<int> idPerfilUsuario, Nullable<int> idArea1, Nullable<int> idArea2, Nullable<int> idArea3, Nullable<int> idArea4, Nullable<int> idArea5, Nullable<int> idCentroCostos1, Nullable<int> idCentroCostos2, Nullable<int> idCentroCostos3, Nullable<int> idCentroCostos4, Nullable<int> idCentroCostos5, Nullable<int> idCentroCostos6, Nullable<int> idCentroCostos7, Nullable<int> idCentroCostos8, Nullable<int> idCentroCostos9, Nullable<int> idCentroCostos10, Nullable<int> idCentroCostos11, Nullable<int> idCentroCostos12, Nullable<int> idCentroCostos13, Nullable<int> idCentroCostos14, Nullable<int> idCentroCostos15, Nullable<int> idUsuarioCC1, Nullable<int> idUsuarioCC2, Nullable<int> idUsuarioCC3, Nullable<int> idUsuarioER1, Nullable<int> idUsuarioER2, Nullable<int> idUsuarioER3, Nullable<int> idUsuarioRE1, Nullable<int> idUsuarioRE2, Nullable<int> idUsuarioRE3, string comentario, string estado, string userCreate, Nullable<System.DateTime> createDate, string userUpdate, Nullable<System.DateTime> updateDate, Nullable<int> tipo2, Nullable<int> idUsuario2)
        {
            var cardCodeParameter = cardCode != null ?
                new ObjectParameter("CardCode", cardCode) :
                new ObjectParameter("CardCode", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var cardNameParameter = cardName != null ?
                new ObjectParameter("CardName", cardName) :
                new ObjectParameter("CardName", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var cantMaxCCParameter = cantMaxCC != null ?
                new ObjectParameter("CantMaxCC", cantMaxCC) :
                new ObjectParameter("CantMaxCC", typeof(string));
    
            var cantMaxERParameter = cantMaxER != null ?
                new ObjectParameter("CantMaxER", cantMaxER) :
                new ObjectParameter("CantMaxER", typeof(string));
    
            var cantMaxREParameter = cantMaxRE != null ?
                new ObjectParameter("CantMaxRE", cantMaxRE) :
                new ObjectParameter("CantMaxRE", typeof(string));
    
            var idPerfilUsuarioParameter = idPerfilUsuario.HasValue ?
                new ObjectParameter("IdPerfilUsuario", idPerfilUsuario) :
                new ObjectParameter("IdPerfilUsuario", typeof(int));
    
            var idArea1Parameter = idArea1.HasValue ?
                new ObjectParameter("IdArea1", idArea1) :
                new ObjectParameter("IdArea1", typeof(int));
    
            var idArea2Parameter = idArea2.HasValue ?
                new ObjectParameter("IdArea2", idArea2) :
                new ObjectParameter("IdArea2", typeof(int));
    
            var idArea3Parameter = idArea3.HasValue ?
                new ObjectParameter("IdArea3", idArea3) :
                new ObjectParameter("IdArea3", typeof(int));
    
            var idArea4Parameter = idArea4.HasValue ?
                new ObjectParameter("IdArea4", idArea4) :
                new ObjectParameter("IdArea4", typeof(int));
    
            var idArea5Parameter = idArea5.HasValue ?
                new ObjectParameter("IdArea5", idArea5) :
                new ObjectParameter("IdArea5", typeof(int));
    
            var idCentroCostos1Parameter = idCentroCostos1.HasValue ?
                new ObjectParameter("IdCentroCostos1", idCentroCostos1) :
                new ObjectParameter("IdCentroCostos1", typeof(int));
    
            var idCentroCostos2Parameter = idCentroCostos2.HasValue ?
                new ObjectParameter("IdCentroCostos2", idCentroCostos2) :
                new ObjectParameter("IdCentroCostos2", typeof(int));
    
            var idCentroCostos3Parameter = idCentroCostos3.HasValue ?
                new ObjectParameter("IdCentroCostos3", idCentroCostos3) :
                new ObjectParameter("IdCentroCostos3", typeof(int));
    
            var idCentroCostos4Parameter = idCentroCostos4.HasValue ?
                new ObjectParameter("IdCentroCostos4", idCentroCostos4) :
                new ObjectParameter("IdCentroCostos4", typeof(int));
    
            var idCentroCostos5Parameter = idCentroCostos5.HasValue ?
                new ObjectParameter("IdCentroCostos5", idCentroCostos5) :
                new ObjectParameter("IdCentroCostos5", typeof(int));
    
            var idCentroCostos6Parameter = idCentroCostos6.HasValue ?
                new ObjectParameter("IdCentroCostos6", idCentroCostos6) :
                new ObjectParameter("IdCentroCostos6", typeof(int));
    
            var idCentroCostos7Parameter = idCentroCostos7.HasValue ?
                new ObjectParameter("IdCentroCostos7", idCentroCostos7) :
                new ObjectParameter("IdCentroCostos7", typeof(int));
    
            var idCentroCostos8Parameter = idCentroCostos8.HasValue ?
                new ObjectParameter("IdCentroCostos8", idCentroCostos8) :
                new ObjectParameter("IdCentroCostos8", typeof(int));
    
            var idCentroCostos9Parameter = idCentroCostos9.HasValue ?
                new ObjectParameter("IdCentroCostos9", idCentroCostos9) :
                new ObjectParameter("IdCentroCostos9", typeof(int));
    
            var idCentroCostos10Parameter = idCentroCostos10.HasValue ?
                new ObjectParameter("IdCentroCostos10", idCentroCostos10) :
                new ObjectParameter("IdCentroCostos10", typeof(int));
    
            var idCentroCostos11Parameter = idCentroCostos11.HasValue ?
                new ObjectParameter("IdCentroCostos11", idCentroCostos11) :
                new ObjectParameter("IdCentroCostos11", typeof(int));
    
            var idCentroCostos12Parameter = idCentroCostos12.HasValue ?
                new ObjectParameter("IdCentroCostos12", idCentroCostos12) :
                new ObjectParameter("IdCentroCostos12", typeof(int));
    
            var idCentroCostos13Parameter = idCentroCostos13.HasValue ?
                new ObjectParameter("IdCentroCostos13", idCentroCostos13) :
                new ObjectParameter("IdCentroCostos13", typeof(int));
    
            var idCentroCostos14Parameter = idCentroCostos14.HasValue ?
                new ObjectParameter("IdCentroCostos14", idCentroCostos14) :
                new ObjectParameter("IdCentroCostos14", typeof(int));
    
            var idCentroCostos15Parameter = idCentroCostos15.HasValue ?
                new ObjectParameter("IdCentroCostos15", idCentroCostos15) :
                new ObjectParameter("IdCentroCostos15", typeof(int));
    
            var idUsuarioCC1Parameter = idUsuarioCC1.HasValue ?
                new ObjectParameter("IdUsuarioCC1", idUsuarioCC1) :
                new ObjectParameter("IdUsuarioCC1", typeof(int));
    
            var idUsuarioCC2Parameter = idUsuarioCC2.HasValue ?
                new ObjectParameter("IdUsuarioCC2", idUsuarioCC2) :
                new ObjectParameter("IdUsuarioCC2", typeof(int));
    
            var idUsuarioCC3Parameter = idUsuarioCC3.HasValue ?
                new ObjectParameter("IdUsuarioCC3", idUsuarioCC3) :
                new ObjectParameter("IdUsuarioCC3", typeof(int));
    
            var idUsuarioER1Parameter = idUsuarioER1.HasValue ?
                new ObjectParameter("IdUsuarioER1", idUsuarioER1) :
                new ObjectParameter("IdUsuarioER1", typeof(int));
    
            var idUsuarioER2Parameter = idUsuarioER2.HasValue ?
                new ObjectParameter("IdUsuarioER2", idUsuarioER2) :
                new ObjectParameter("IdUsuarioER2", typeof(int));
    
            var idUsuarioER3Parameter = idUsuarioER3.HasValue ?
                new ObjectParameter("IdUsuarioER3", idUsuarioER3) :
                new ObjectParameter("IdUsuarioER3", typeof(int));
    
            var idUsuarioRE1Parameter = idUsuarioRE1.HasValue ?
                new ObjectParameter("IdUsuarioRE1", idUsuarioRE1) :
                new ObjectParameter("IdUsuarioRE1", typeof(int));
    
            var idUsuarioRE2Parameter = idUsuarioRE2.HasValue ?
                new ObjectParameter("IdUsuarioRE2", idUsuarioRE2) :
                new ObjectParameter("IdUsuarioRE2", typeof(int));
    
            var idUsuarioRE3Parameter = idUsuarioRE3.HasValue ?
                new ObjectParameter("IdUsuarioRE3", idUsuarioRE3) :
                new ObjectParameter("IdUsuarioRE3", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var userCreateParameter = userCreate != null ?
                new ObjectParameter("UserCreate", userCreate) :
                new ObjectParameter("UserCreate", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var userUpdateParameter = userUpdate != null ?
                new ObjectParameter("UserUpdate", userUpdate) :
                new ObjectParameter("UserUpdate", typeof(string));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var tipo2Parameter = tipo2.HasValue ?
                new ObjectParameter("Tipo2", tipo2) :
                new ObjectParameter("Tipo2", typeof(int));
    
            var idUsuario2Parameter = idUsuario2.HasValue ?
                new ObjectParameter("IdUsuario2", idUsuario2) :
                new ObjectParameter("IdUsuario2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_UsuarioInsertar", cardCodeParameter, passParameter, cardNameParameter, tipoParameter, phoneParameter, mailParameter, cantMaxCCParameter, cantMaxERParameter, cantMaxREParameter, idPerfilUsuarioParameter, idArea1Parameter, idArea2Parameter, idArea3Parameter, idArea4Parameter, idArea5Parameter, idCentroCostos1Parameter, idCentroCostos2Parameter, idCentroCostos3Parameter, idCentroCostos4Parameter, idCentroCostos5Parameter, idCentroCostos6Parameter, idCentroCostos7Parameter, idCentroCostos8Parameter, idCentroCostos9Parameter, idCentroCostos10Parameter, idCentroCostos11Parameter, idCentroCostos12Parameter, idCentroCostos13Parameter, idCentroCostos14Parameter, idCentroCostos15Parameter, idUsuarioCC1Parameter, idUsuarioCC2Parameter, idUsuarioCC3Parameter, idUsuarioER1Parameter, idUsuarioER2Parameter, idUsuarioER3Parameter, idUsuarioRE1Parameter, idUsuarioRE2Parameter, idUsuarioRE3Parameter, comentarioParameter, estadoParameter, userCreateParameter, createDateParameter, userUpdateParameter, updateDateParameter, tipo2Parameter, idUsuario2Parameter);
        }
    
        public virtual ObjectResult<MSS_WEB_UsuarioListar_Result> MSS_WEB_UsuarioListar(Nullable<int> tipo2, Nullable<int> idUsuario2, Nullable<int> tipo3)
        {
            var tipo2Parameter = tipo2.HasValue ?
                new ObjectParameter("Tipo2", tipo2) :
                new ObjectParameter("Tipo2", typeof(int));
    
            var idUsuario2Parameter = idUsuario2.HasValue ?
                new ObjectParameter("IdUsuario2", idUsuario2) :
                new ObjectParameter("IdUsuario2", typeof(int));
    
            var tipo3Parameter = tipo3.HasValue ?
                new ObjectParameter("Tipo3", tipo3) :
                new ObjectParameter("Tipo3", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_UsuarioListar_Result>("MSS_WEB_UsuarioListar", tipo2Parameter, idUsuario2Parameter, tipo3Parameter);
        }
    
        public virtual ObjectResult<MSS_WEB_UsuarioListar2_Result> MSS_WEB_UsuarioListar2(Nullable<int> tipo2, Nullable<int> tipo3, Nullable<int> tipo4, string palabra)
        {
            var tipo2Parameter = tipo2.HasValue ?
                new ObjectParameter("Tipo2", tipo2) :
                new ObjectParameter("Tipo2", typeof(int));
    
            var tipo3Parameter = tipo3.HasValue ?
                new ObjectParameter("Tipo3", tipo3) :
                new ObjectParameter("Tipo3", typeof(int));
    
            var tipo4Parameter = tipo4.HasValue ?
                new ObjectParameter("Tipo4", tipo4) :
                new ObjectParameter("Tipo4", typeof(int));
    
            var palabraParameter = palabra != null ?
                new ObjectParameter("Palabra", palabra) :
                new ObjectParameter("Palabra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_UsuarioListar2_Result>("MSS_WEB_UsuarioListar2", tipo2Parameter, tipo3Parameter, tipo4Parameter, palabraParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_UsuarioLogin_Result> MSS_WEB_UsuarioLogin(string cardCode, string pass)
        {
            var cardCodeParameter = cardCode != null ?
                new ObjectParameter("CardCode", cardCode) :
                new ObjectParameter("CardCode", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_UsuarioLogin_Result>("MSS_WEB_UsuarioLogin", cardCodeParameter, passParameter);
        }
    
        public virtual int MSS_WEB_UsuarioModificar(Nullable<int> idUsuario, string cardCode, string pass, string cardName, string tipo, string phone, string mail, string cantMaxCC, string cantMaxER, string cantMaxRE, Nullable<int> idPerfilUsuario, Nullable<int> idArea1, Nullable<int> idArea2, Nullable<int> idArea3, Nullable<int> idArea4, Nullable<int> idArea5, Nullable<int> idCentroCostos1, Nullable<int> idCentroCostos2, Nullable<int> idCentroCostos3, Nullable<int> idCentroCostos4, Nullable<int> idCentroCostos5, Nullable<int> idCentroCostos6, Nullable<int> idCentroCostos7, Nullable<int> idCentroCostos8, Nullable<int> idCentroCostos9, Nullable<int> idCentroCostos10, Nullable<int> idCentroCostos11, Nullable<int> idCentroCostos12, Nullable<int> idCentroCostos13, Nullable<int> idCentroCostos14, Nullable<int> idCentroCostos15, Nullable<int> idUsuarioCC1, Nullable<int> idUsuarioCC2, Nullable<int> idUsuarioCC3, Nullable<int> idUsuarioER1, Nullable<int> idUsuarioER2, Nullable<int> idUsuarioER3, Nullable<int> idUsuarioRE1, Nullable<int> idUsuarioRE2, Nullable<int> idUsuarioRE3, string comentario, string estado, string userCreate, Nullable<System.DateTime> createDate, string userUpdate, Nullable<System.DateTime> updateDate)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var cardCodeParameter = cardCode != null ?
                new ObjectParameter("CardCode", cardCode) :
                new ObjectParameter("CardCode", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var cardNameParameter = cardName != null ?
                new ObjectParameter("CardName", cardName) :
                new ObjectParameter("CardName", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var cantMaxCCParameter = cantMaxCC != null ?
                new ObjectParameter("CantMaxCC", cantMaxCC) :
                new ObjectParameter("CantMaxCC", typeof(string));
    
            var cantMaxERParameter = cantMaxER != null ?
                new ObjectParameter("CantMaxER", cantMaxER) :
                new ObjectParameter("CantMaxER", typeof(string));
    
            var cantMaxREParameter = cantMaxRE != null ?
                new ObjectParameter("CantMaxRE", cantMaxRE) :
                new ObjectParameter("CantMaxRE", typeof(string));
    
            var idPerfilUsuarioParameter = idPerfilUsuario.HasValue ?
                new ObjectParameter("IdPerfilUsuario", idPerfilUsuario) :
                new ObjectParameter("IdPerfilUsuario", typeof(int));
    
            var idArea1Parameter = idArea1.HasValue ?
                new ObjectParameter("IdArea1", idArea1) :
                new ObjectParameter("IdArea1", typeof(int));
    
            var idArea2Parameter = idArea2.HasValue ?
                new ObjectParameter("IdArea2", idArea2) :
                new ObjectParameter("IdArea2", typeof(int));
    
            var idArea3Parameter = idArea3.HasValue ?
                new ObjectParameter("IdArea3", idArea3) :
                new ObjectParameter("IdArea3", typeof(int));
    
            var idArea4Parameter = idArea4.HasValue ?
                new ObjectParameter("IdArea4", idArea4) :
                new ObjectParameter("IdArea4", typeof(int));
    
            var idArea5Parameter = idArea5.HasValue ?
                new ObjectParameter("IdArea5", idArea5) :
                new ObjectParameter("IdArea5", typeof(int));
    
            var idCentroCostos1Parameter = idCentroCostos1.HasValue ?
                new ObjectParameter("IdCentroCostos1", idCentroCostos1) :
                new ObjectParameter("IdCentroCostos1", typeof(int));
    
            var idCentroCostos2Parameter = idCentroCostos2.HasValue ?
                new ObjectParameter("IdCentroCostos2", idCentroCostos2) :
                new ObjectParameter("IdCentroCostos2", typeof(int));
    
            var idCentroCostos3Parameter = idCentroCostos3.HasValue ?
                new ObjectParameter("IdCentroCostos3", idCentroCostos3) :
                new ObjectParameter("IdCentroCostos3", typeof(int));
    
            var idCentroCostos4Parameter = idCentroCostos4.HasValue ?
                new ObjectParameter("IdCentroCostos4", idCentroCostos4) :
                new ObjectParameter("IdCentroCostos4", typeof(int));
    
            var idCentroCostos5Parameter = idCentroCostos5.HasValue ?
                new ObjectParameter("IdCentroCostos5", idCentroCostos5) :
                new ObjectParameter("IdCentroCostos5", typeof(int));
    
            var idCentroCostos6Parameter = idCentroCostos6.HasValue ?
                new ObjectParameter("IdCentroCostos6", idCentroCostos6) :
                new ObjectParameter("IdCentroCostos6", typeof(int));
    
            var idCentroCostos7Parameter = idCentroCostos7.HasValue ?
                new ObjectParameter("IdCentroCostos7", idCentroCostos7) :
                new ObjectParameter("IdCentroCostos7", typeof(int));
    
            var idCentroCostos8Parameter = idCentroCostos8.HasValue ?
                new ObjectParameter("IdCentroCostos8", idCentroCostos8) :
                new ObjectParameter("IdCentroCostos8", typeof(int));
    
            var idCentroCostos9Parameter = idCentroCostos9.HasValue ?
                new ObjectParameter("IdCentroCostos9", idCentroCostos9) :
                new ObjectParameter("IdCentroCostos9", typeof(int));
    
            var idCentroCostos10Parameter = idCentroCostos10.HasValue ?
                new ObjectParameter("IdCentroCostos10", idCentroCostos10) :
                new ObjectParameter("IdCentroCostos10", typeof(int));
    
            var idCentroCostos11Parameter = idCentroCostos11.HasValue ?
                new ObjectParameter("IdCentroCostos11", idCentroCostos11) :
                new ObjectParameter("IdCentroCostos11", typeof(int));
    
            var idCentroCostos12Parameter = idCentroCostos12.HasValue ?
                new ObjectParameter("IdCentroCostos12", idCentroCostos12) :
                new ObjectParameter("IdCentroCostos12", typeof(int));
    
            var idCentroCostos13Parameter = idCentroCostos13.HasValue ?
                new ObjectParameter("IdCentroCostos13", idCentroCostos13) :
                new ObjectParameter("IdCentroCostos13", typeof(int));
    
            var idCentroCostos14Parameter = idCentroCostos14.HasValue ?
                new ObjectParameter("IdCentroCostos14", idCentroCostos14) :
                new ObjectParameter("IdCentroCostos14", typeof(int));
    
            var idCentroCostos15Parameter = idCentroCostos15.HasValue ?
                new ObjectParameter("IdCentroCostos15", idCentroCostos15) :
                new ObjectParameter("IdCentroCostos15", typeof(int));
    
            var idUsuarioCC1Parameter = idUsuarioCC1.HasValue ?
                new ObjectParameter("IdUsuarioCC1", idUsuarioCC1) :
                new ObjectParameter("IdUsuarioCC1", typeof(int));
    
            var idUsuarioCC2Parameter = idUsuarioCC2.HasValue ?
                new ObjectParameter("IdUsuarioCC2", idUsuarioCC2) :
                new ObjectParameter("IdUsuarioCC2", typeof(int));
    
            var idUsuarioCC3Parameter = idUsuarioCC3.HasValue ?
                new ObjectParameter("IdUsuarioCC3", idUsuarioCC3) :
                new ObjectParameter("IdUsuarioCC3", typeof(int));
    
            var idUsuarioER1Parameter = idUsuarioER1.HasValue ?
                new ObjectParameter("IdUsuarioER1", idUsuarioER1) :
                new ObjectParameter("IdUsuarioER1", typeof(int));
    
            var idUsuarioER2Parameter = idUsuarioER2.HasValue ?
                new ObjectParameter("IdUsuarioER2", idUsuarioER2) :
                new ObjectParameter("IdUsuarioER2", typeof(int));
    
            var idUsuarioER3Parameter = idUsuarioER3.HasValue ?
                new ObjectParameter("IdUsuarioER3", idUsuarioER3) :
                new ObjectParameter("IdUsuarioER3", typeof(int));
    
            var idUsuarioRE1Parameter = idUsuarioRE1.HasValue ?
                new ObjectParameter("IdUsuarioRE1", idUsuarioRE1) :
                new ObjectParameter("IdUsuarioRE1", typeof(int));
    
            var idUsuarioRE2Parameter = idUsuarioRE2.HasValue ?
                new ObjectParameter("IdUsuarioRE2", idUsuarioRE2) :
                new ObjectParameter("IdUsuarioRE2", typeof(int));
    
            var idUsuarioRE3Parameter = idUsuarioRE3.HasValue ?
                new ObjectParameter("IdUsuarioRE3", idUsuarioRE3) :
                new ObjectParameter("IdUsuarioRE3", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var userCreateParameter = userCreate != null ?
                new ObjectParameter("UserCreate", userCreate) :
                new ObjectParameter("UserCreate", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var userUpdateParameter = userUpdate != null ?
                new ObjectParameter("UserUpdate", userUpdate) :
                new ObjectParameter("UserUpdate", typeof(string));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_UsuarioModificar", idUsuarioParameter, cardCodeParameter, passParameter, cardNameParameter, tipoParameter, phoneParameter, mailParameter, cantMaxCCParameter, cantMaxERParameter, cantMaxREParameter, idPerfilUsuarioParameter, idArea1Parameter, idArea2Parameter, idArea3Parameter, idArea4Parameter, idArea5Parameter, idCentroCostos1Parameter, idCentroCostos2Parameter, idCentroCostos3Parameter, idCentroCostos4Parameter, idCentroCostos5Parameter, idCentroCostos6Parameter, idCentroCostos7Parameter, idCentroCostos8Parameter, idCentroCostos9Parameter, idCentroCostos10Parameter, idCentroCostos11Parameter, idCentroCostos12Parameter, idCentroCostos13Parameter, idCentroCostos14Parameter, idCentroCostos15Parameter, idUsuarioCC1Parameter, idUsuarioCC2Parameter, idUsuarioCC3Parameter, idUsuarioER1Parameter, idUsuarioER2Parameter, idUsuarioER3Parameter, idUsuarioRE1Parameter, idUsuarioRE2Parameter, idUsuarioRE3Parameter, comentarioParameter, estadoParameter, userCreateParameter, createDateParameter, userUpdateParameter, updateDateParameter);
        }
    
        public virtual int MSS_WEB_UsuarioModificarContrasena(string cardCode, string pass)
        {
            var cardCodeParameter = cardCode != null ?
                new ObjectParameter("CardCode", cardCode) :
                new ObjectParameter("CardCode", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSS_WEB_UsuarioModificarContrasena", cardCodeParameter, passParameter);
        }
    
        public virtual ObjectResult<MSS_WEB_UsuarioObtener_Result> MSS_WEB_UsuarioObtener(Nullable<int> idUsuario, Nullable<int> tipo)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MSS_WEB_UsuarioObtener_Result>("MSS_WEB_UsuarioObtener", idUsuarioParameter, tipoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MSS_WEB_UsuarioVerificar(string cardCode)
        {
            var cardCodeParameter = cardCode != null ?
                new ObjectParameter("CardCode", cardCode) :
                new ObjectParameter("CardCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MSS_WEB_UsuarioVerificar", cardCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MSS_WEB_UsuarioVerificar2(Nullable<int> cardCode, string mail)
        {
            var cardCodeParameter = cardCode.HasValue ?
                new ObjectParameter("CardCode", cardCode) :
                new ObjectParameter("CardCode", typeof(int));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MSS_WEB_UsuarioVerificar2", cardCodeParameter, mailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MSS_WEB_UsuarioVerificarExiste(Nullable<int> cardCode)
        {
            var cardCodeParameter = cardCode.HasValue ?
                new ObjectParameter("CardCode", cardCode) :
                new ObjectParameter("CardCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MSS_WEB_UsuarioVerificarExiste", cardCodeParameter);
        }
    }
}
