//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SICER_WEBEntities1 : DbContext
    {
        public SICER_WEBEntities1()
            : base("name=SICER_WEBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<DocumentoWeb> DocumentoWeb { get; set; }
        public virtual DbSet<DocumentoWebAuditoria> DocumentoWebAuditoria { get; set; }
        public virtual DbSet<DocumentoWebRendicion> DocumentoWebRendicion { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<MetodoPago> MetodoPago { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Acceso> Acceso { get; set; }
        public virtual DbSet<Aprobacion> Aprobacion { get; set; }
        public virtual DbSet<Concepto> Concepto { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<NivelAprobacion> NivelAprobacion { get; set; }
        public virtual DbSet<PerfilUsuario> PerfilUsuario { get; set; }
        public virtual DbSet<UsuarioAreaNivel> UsuarioAreaNivel { get; set; }
        public virtual DbSet<EmpresasSICER> EmpresasSICER { get; set; }
    }
}
