//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SICER_WEBEntities : DbContext
    {
        public SICER_WEBEntities()
            : base("name=SICER_WEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONFIG> CONFIG { get; set; }
        public virtual DbSet<DocumentoWeb> DocumentoWeb { get; set; }
        public virtual DbSet<DocumentoWebAuditoria> DocumentoWebAuditoria { get; set; }
        public virtual DbSet<DocumentoWebRendicion> DocumentoWebRendicion { get; set; }
        public virtual DbSet<FacturasWebMigracion> FacturasWebMigracion { get; set; }
        public virtual DbSet<MaestroTrabajadores> MaestroTrabajadores { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<NivelAprobacion> NivelAprobacion { get; set; }
        public virtual DbSet<PerfilUsuario> PerfilUsuario { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
    }
}
