//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_DOCU_RETE
    {
        public string CO_IDEN { get; set; }
        public string NU_RUCS { get; set; }
        public string DE_EMPR { get; set; }
        public string DE_COME { get; set; }
        public string DE_DIRE { get; set; }
        public string CO_UBIG { get; set; }
        public string DE_PROV { get; set; }
        public string DE_DPTO { get; set; }
        public string DE_DIST { get; set; }
        public string CO_PAIS { get; set; }
        public string CO_IDEN_DEST { get; set; }
        public string NU_RUCS_DEST { get; set; }
        public string DE_EMPR_DEST { get; set; }
        public string CO_UBIG_DEST { get; set; }
        public string DE_DIRE_DEST { get; set; }
        public string DE_PROV_DEST { get; set; }
        public string DE_DPTO_DEST { get; set; }
        public string DE_DIST_DEST { get; set; }
        public string CO_PAIS_DEST { get; set; }
        public string DE_EMAI_DEST { get; set; }
        public Nullable<System.DateTime> FE_EMIS { get; set; }
        public string DE_MOTI { get; set; }
        public string CO_TIPO_DOCU { get; set; }
        public string CO_SERI { get; set; }
        public string NU_CORR { get; set; }
        public string DE_OBSE { get; set; }
        public string CO_ESTA { get; set; }
        public string CO_VERS_UBL { get; set; }
        public string CO_VERS_ESTR { get; set; }
        public string NU_ORDE { get; set; }
        public string DE_OPER_LETR { get; set; }
        public string CO_ESTA_RESU { get; set; }
        public string CO_REGI_RETE { get; set; }
        public string CO_SERI_DREL { get; set; }
        public string NU_CORR_DREL { get; set; }
        public string CO_TIPO_DREL { get; set; }
        public Nullable<System.DateTime> FE_EMIS_DREL { get; set; }
        public string NU_TASA_RETE { get; set; }
        public Nullable<decimal> NU_TOTA_RETE { get; set; }
        public string CO_MONE_RETE { get; set; }
        public Nullable<decimal> NU_TOTA_PAGA { get; set; }
        public string CO_MONE_PAGA { get; set; }
        public string TI_DREL_RETE { get; set; }
        public string NU_DREL_RETE { get; set; }
        public Nullable<System.DateTime> FE_EMIS_RETE { get; set; }
        public Nullable<decimal> NU_TOTA_DREL { get; set; }
        public string CO_MONE_DREL { get; set; }
        public Nullable<System.DateTime> FE_PAGO { get; set; }
        public string NU_PAGO { get; set; }
        public Nullable<decimal> NU_PAGO_SRET { get; set; }
        public string CO_MONE_PAGO { get; set; }
        public Nullable<decimal> NU_IMPO_RETE { get; set; }
        public string CO_MONE_IMPR { get; set; }
        public Nullable<System.DateTime> FE_RETE { get; set; }
        public Nullable<decimal> NU_IMPO_PAGO { get; set; }
        public string CO_MONE_MNPA { get; set; }
        public string CO_MONE_TCAM { get; set; }
        public string CO_MONE_OBJE { get; set; }
        public Nullable<decimal> NU_FACT_MONE { get; set; }
        public Nullable<System.DateTime> FE_CAMB { get; set; }
    }
}
