//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.DocumentoWeb = new HashSet<DocumentoWeb>();
            this.DocumentoWeb1 = new HashSet<DocumentoWeb>();
            this.DocumentoWeb2 = new HashSet<DocumentoWeb>();
            this.DocumentoWebAuditoria = new HashSet<DocumentoWebAuditoria>();
            this.DocumentoWebRendicion = new HashSet<DocumentoWebRendicion>();
            this.DocumentoWebRendicion1 = new HashSet<DocumentoWebRendicion>();
            this.DocumentoWebRendicion2 = new HashSet<DocumentoWebRendicion>();
            this.DocumentoWebRendicion3 = new HashSet<DocumentoWebRendicion>();
            this.DocumentoWebRendicion4 = new HashSet<DocumentoWebRendicion>();
            this.DocumentoWebRendicion5 = new HashSet<DocumentoWebRendicion>();
        }
    
        public int IdUsuario { get; set; }
        public string CardCode { get; set; }
        public byte[] Pass { get; set; }
        public string CardName { get; set; }
        public string Tipo { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string CantMaxCC { get; set; }
        public string CantMaxER { get; set; }
        public string CantMaxRE { get; set; }
        public Nullable<int> IdPerfilUsuario { get; set; }
        public Nullable<int> IdArea1 { get; set; }
        public Nullable<int> IdArea2 { get; set; }
        public Nullable<int> IdArea3 { get; set; }
        public Nullable<int> IdArea4 { get; set; }
        public Nullable<int> IdArea5 { get; set; }
        public Nullable<int> IdCentroCostos1 { get; set; }
        public Nullable<int> IdCentroCostos2 { get; set; }
        public Nullable<int> IdCentroCostos3 { get; set; }
        public Nullable<int> IdCentroCostos4 { get; set; }
        public Nullable<int> IdCentroCostos5 { get; set; }
        public Nullable<int> IdCentroCostos6 { get; set; }
        public Nullable<int> IdCentroCostos7 { get; set; }
        public Nullable<int> IdCentroCostos8 { get; set; }
        public Nullable<int> IdCentroCostos9 { get; set; }
        public Nullable<int> IdUsuarioCC1 { get; set; }
        public Nullable<int> IdUsuarioCC2 { get; set; }
        public Nullable<int> IdUsuarioCC3 { get; set; }
        public Nullable<int> IdUsuarioER1 { get; set; }
        public Nullable<int> IdUsuarioER2 { get; set; }
        public Nullable<int> IdUsuarioER3 { get; set; }
        public Nullable<int> IdUsuarioRE1 { get; set; }
        public Nullable<int> IdUsuarioRE2 { get; set; }
        public Nullable<int> IdUsuarioRE3 { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
        public string IntentoLogin { get; set; }
        public Nullable<System.DateTime> HoraMinutoLogin { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> IdCentroCostos10 { get; set; }
        public Nullable<int> IdCentroCostos11 { get; set; }
        public Nullable<int> IdCentroCostos12 { get; set; }
        public Nullable<int> IdCentroCostos13 { get; set; }
        public Nullable<int> IdCentroCostos14 { get; set; }
        public Nullable<int> IdCentroCostos15 { get; set; }
        public Nullable<bool> UsuarioTesoreria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWeb> DocumentoWeb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWeb> DocumentoWeb1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWeb> DocumentoWeb2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebAuditoria> DocumentoWebAuditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoWebRendicion> DocumentoWebRendicion5 { get; set; }
    }
}
