//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.TAWA.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VERS
    {
        public string CO_VERS_UBL { get; set; }
        public string CO_VERS_ESTR { get; set; }
    }
}
